spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/serverissues
    username: root
    password: admin
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080
